WalkingPal/walking-pal-web

- package.json
- pages/home/Home.tsx
- yarn.lock
YT video on homepage started as soon as page loaded.
Used react intersection observer to detect when the video enters viewport and then triggering play accordingly.
fixes #21
> fix(home): added react intersection observer

- components/Footer/Footer.tsx
- components/Header/components/List1.tsx
- pages/_document.pg.tsx
- pages/home/components/EasySteps.tsx
- pages/home/components/EasyStepsFooter.tsx
- pages/home/components/ReImagineYourDailyCommute.tsx
- #30
Altered the following things for the homepage:
* Text in navbar (made it darker for more contrast)
* Text in 'Get your walking buddy' section (made it darker for more contrast) 
*  Text in 'Microsoft Partner' section (made it white instead of dark gray)
*  Text in 'Reimagine your daily commute'  section (made it bold instead of highlighted for more contrast)
*  Added alt text to the commute illustrations
*  Added a lang attribute to the HTML tag for screen readers
*  Added aria-labels to the social media icons for screen readers
> fix: accessibility issues homepage

- components/Header/components/List1.tsx
Closes #61 
- Added a ListItem as a direct child of List and wrapped ListItemButton inside it
- Updated ListItemButton to be an anchor element
- Removed the extra Link element surrounding the text in order to remove the double tab stop
These buttons are now more accessible :)
> fix: use correct semantic elements in header nav

- .docs/CONTRIBUTING.md
CONTRIBUTING.md for issue #48
Spelling and grammatical changes in docs/CONTRIBUTING.md. 
I also changed:
*  instances of "participants/contributors" to just "contributors" and "maintainers/mentors" to "maintainers" for simplicity.
* the word "Issue" to lowercase "issue" to match Github's docs.
> docs: contributing.md typos and grammar

- components/SlideIn/SlideIn.tsx
- components/SlideIn/index.ts
- Added SlideIn animation component
- Closes #49 
- Usage Example
```
<SlideIn>
<div>
<OurStory />
</div>
</SlideIn>
```
https://user-images.githubusercontent.com/59320016/194384933-c318443f-091f-41ae-be59-337b46761511.mov
> feat(slideIn): add a SlideIn animation component

- pages/register/components/InputField.tsx
- pages/register/components/RegistrationForm.tsx
> feat(register): input field autoFocus

- components/SlideEach/SlideEach.tsx
- components/SlideEach/index.ts
- components/SlideIn/SlideIn.tsx
> feat: slideEach-component

- .docs/CODE-OF-CONDUCT.md
> docs: corrections in CODE-OF-CONDUCT.md

- .docs/PROJECT-GUIDELINES.md
fixes typos in [PROJECT-GUIDELINES.md](https://github.com/WalkingPal/walking-pal-web/blob/dev/.docs/PROJECT-GUIDELINES.md) for issue #48
> docs: corrections in PROJECT-GUIDELINES.md

- README.md
fixes typo errors in [README.md](https://github.com/WalkingPal/walking-pal-web/blob/dev/README.md) for issue #48
> docs: corrections in README.md

- .docs/CONTRIBUTING.md
> docs: Coloured segments in Contributing Guidelines

- components/Header/Header.tsx
- pages/_globals.scss
Fix added:
- Navbar and page flickering on page navigation
closes #106
> fix: nav flicker bug fix

- components/PageTransition/PageTransition.tsx
- components/PageTransition/index.tsx
- package.json
- pages/_app.pg.tsx
- yarn.lock
Feature:
- Added Page linear transition on navigation between pages.
closes #101
> feat: page linear transition added

- pages/company/Company.tsx
- pages/company/components/Hero.tsx
fixes #109 by adding height and width to the image
> fix: card size in company page

- pages/home/components/ReImagineYourDailyCommute.tsx
Responsive card design updated for screen width >900
Fixes : #102
> style(home): ReImagine Cards layout

- components/Header/Header.tsx
- pages/home/Home.tsx
- pages/home/components/Intro.tsx
- pages/home/components/RibbonsSection.tsx
- fixes scroll lag in homepage
> perf: memoize RibbonsSection component

- components/FeedbackForm/FeedbackForm.tsx
- components/FeedbackForm/formValidation.ts
- components/Header/components/List2.tsx
- pages/register/components/FormActions.tsx
- pages/register/components/InputField.tsx
- pages/register/components/SubmittedAck.tsx
- pages/register/register.module.scss
- theme/theme.ts
- utils/db/textTransform.ts
> feat(register): university option

- package.json
- pages/api/early-user/index.pg.ts
- pages/api/feedback/index.pg.ts
- yarn.lock
1. Added zod for schema validation
2. Created schemas for formData and captcha for /early-user and /feedback
3. Schemas parse the formData and captcha and validate
4. Phone number is kept optional in /feedback as it was not a required field in the UI on client side. If phone number not provided , it will be stored as ""
- closes #89
> Feat: Add Zod Validations for APIs

- pages/_app.pg.tsx
- pages/about/About.tsx
- pages/blog/Blog.tsx
- pages/company/Company.tsx
- pages/faq/FAQ.tsx
- pages/home/Home.tsx
Refactored scroll-to-top button in App file instead of repeating it in every page file.
- closes #152
> chore: refactored scroll-to-top button

- components/FeedbackForm/components/formValidation.ts
- pages/api/early-user/index.pg.ts
- pages/api/feedback/index.pg.ts
- pages/register/components/formValidation.ts
- fixes #156
Trimming the string before the validation so that spaces are removed and hence strings with empty spaces will no longer be accepted for first and last name.
Preview
https://user-images.githubusercontent.com/56157504/197939527-87348bc4-4ebb-4e8b-bd4d-8aca190951a2.mp4
> fix: Reject strings with spaces for first and last name on register page

- components/FeedbackForm/components/FormHeader.tsx
- pages/faq/components/FAQsection.tsx
- pages/faq/components/Hero.tsx
- pages/faq/faq.module.scss
Accessibility improvements - FAQ
Issue: bug: need accessibility improvements #123
> bug: Need accessibility improvements

- pages/404/404.tsx
- pages/register/Register.tsx
- pages/register/components/InputField.tsx
Accessibility improvements
- Register
- 404
closes #123
> Accessibility improvements

- package.json
- pages/api/early-user/index.pg.ts
- yarn.lock
- Email validation using [deep-email-validator](https://github.com/mfbx9da4/deep-email-validator)
- closes #137
-
> :tada: [feat]: Email validation with MX records (#137)
